/// Flutter icons AppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const _kFontPkg = null;

  static const IconData cabinet_drawer = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolbox = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools_things = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toys_things = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cabinet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData living_room = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room_door = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
